apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: perf-demo
type: Opaque
stringData:
  USER_DB_URL:    "postgresql://postgres:postgres@user-db:5432/userdb"
  PRODUCT_DB_URL: "postgresql://postgres:postgres@product-db:5432/productdb"
  ORDER_DB_URL:   "postgresql://postgres:postgres@order-db:5432/orderdb"
